config/routes.rb
Nethermead::Application.routes.draw do
  get "search_results/show"

  root 'search#index'

  get 'search' => 'search#index'
  get 'companies' => 'search#companies'
  post 'search' => 'search#find'
  
  get 'search/:slug/:state/:class' => 'search#show'
  get 'search/:slug/:state/:class/map' => 'search#map'
  get 'search/:slug/:state/:class/export' => 'search#export'
  post 'search/:slug/:state/:class/share' => 'search#share'

  get 'company/:id/markets' => 'company#markets'

  resources :search_results
  resources :interested_users

end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/county.rb
class County < ActiveRecord::Base
end

app/models/interested_user.rb
class InterestedUser < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, :with => /@/
end

app/models/product_class.rb
class ProductClass < ActiveRecord::Base
end

app/models/search_result.rb
class SearchResult < ActiveRecord::Base
  belongs_to :company
  belongs_to :product_class
  belongs_to :state
  has_many :search_results_county

  def state_competition
    SearchResultsCompetitor.where(:product_class_id => product_class_id, :state_id => state_id).order(rank_order: :asc).pluck(:company_name, :market_share, :company_id)
  end
  
  def competitor_url(company_id)
		'/search/' + Company.find(company_id).slug + '/' + self.state_name.downcase + '/' + self.product_class.abbr.downcase
  end

  def market_segments
    SearchResultsSegment.where(:product_class_id => product_class_id, :state_id => state_id).order(rank_order: :asc)
  end

  def percentage_market_share
    if share_company_in_state
      return (share_company_in_state * 100).to_int
    end
    return 20
  end
end

app/models/search_results_competitor.rb
class SearchResultsCompetitor < ActiveRecord::Base
end

app/models/search_results_counties_segment.rb
class SearchResultsCountiesSegment < ActiveRecord::Base
end

app/models/search_results_county.rb
class SearchResultsCounty < ActiveRecord::Base
end

app/models/search_results_segment.rb
class SearchResultsSegment < ActiveRecord::Base
	belongs_to :segment
end

app/models/segment.rb
class Segment < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
  def abbreviation
    state_name.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  http_basic_authenticate_with name: "nethermead", password: "12345!@#$%"
  
  protect_from_forgery with: :exception
  before_action :set_interested_user
  
  has_mobile_fu

  def set_interested_user
    @interested_user = InterestedUser.new
  end
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  respond_to :json

  def markets
    headers['Last-Modified'] = Time.now.httpdate
    company = Company.find(params[:id])
    t = SearchResult.arel_table
    respond_with SearchResult.where(company_id: company.id).order(:state_name).as_json(
                     :only => [ :state, :product_class, :id ], :include => [ :state, :product_class ])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  respond_to :html, :json
  layout "search"

  def index
    @search_result = SearchResult.new
  end

  def find
    t = SearchResult.arel_table
    @result = SearchResult.where(
                t[:company_name].matches(params[:search_result][:company_name])
                .and(t[:state_name].eq(params[:search_result][:state_name]))
                .and(t[:product_class].eq(params[:search_result][:product_class]))
                ).first
    if @result
      redirect_to search_result_path @result
    else
      flash[:notice] = "Whoops. No matching combination."
      redirect_to search_path
    end
  end

  def show
    company = Company.where(Company.arel_table[:slug].matches(params[:slug])).first
    state = State.where(State.arel_table[:state_name].matches(params[:state].upcase)).first
    product_class = ProductClass.where(ProductClass.arel_table[:abbr].matches(params[:class].upcase)).first
    @result = SearchResult.where(
        company_id: company.id,
        state_id: state.id,
        product_class_id: product_class.id
    ).first
  end
  
  def map
  	company = Company.where(Company.arel_table[:slug].matches(params[:slug])).first
    state = State.where(State.arel_table[:state_name].matches(params[:state].upcase)).first
    product_class = ProductClass.where(ProductClass.arel_table[:abbr].matches(params[:class].upcase)).first
    @result = SearchResult.where(
        company_id: company.id,
        state_id: state.id,
        product_class_id: product_class.id
    ).first
  end

  def export
    show
    response.headers['Content-Type'] = 'text/csv'
    csv_string = CSV.generate do |csv|
      csv << @result.attribute_names
      csv << @result.attributes.values
    end
    send_data csv_string
  end

  def share
    show
    if params[:email] && params[:email].match(/@/) && params[:message]
      url = url_for :controller => 'search', :action => 'show', :slug => @result.company.slug, :state => @result.state.state_name, :class => @result.product_class.abbr, :only_path => false
      ShareMailer.share(params[:email], url, params[:message]).deliver
    end
    flash[:notice] = "Thank you for sharing this result!"
    redirect_to url_for :controller => 'search', :action => 'show', :slug => @result.company.slug, :state => @result.state.state_name, :class => @result.product_class.abbr
  end

  def companies
    t = Company.arel_table
    respond_with Company.where(
        t[:name_proper].matches("%" + params[:company_name] + "%")
    ).as_json
  end

end

app/controllers/search_results_controller.rb
class SearchResultsController < ApplicationController
  def show
  	@r = SearchResult.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/interested_users_helper.rb
module InterestedUsersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/search_results_helper.rb
module SearchResultsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nethermead</title>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

  
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid" id="main-navigation" >
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img src="<%= asset_path('logo.png')%>"/></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="#">Start</a></li>
        <li><a href="#">Product</a></li>
        <li><a href="#">About</a></li>
        <!--
<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="interested-user-container">
    <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <%= form_for :interested_user, url: interested_users_path, html: {class: 'form form-inline pull-right'} do |f| %>
              <%= f.text_field :email, class: 'form-control', placeholder: 'Enter email' %>
              <%= f.submit :'Submit', class: 'btn' %>
            <% end %>
            <span class="title">Sign up to learn more about your market, consumers, and Nethermead.</span>
          </div>
        </div>
    </div>
</div>


<% if flash[:notice] %>
  <div class="container-fluid">
    <div class="notice"><%= flash[:notice] %></div>
  </div>
<% end %>
<%= content_for?(:content) ? yield(:content) : yield %>

<%= javascript_include_tag "application", "data-turbolinks-track" => true %>

<% unless is_mobile_device? %>
<script type="text/javascript" src="https://s3.amazonaws.com/assets.freshdesk.com/widget/freshwidget.js"></script>
<script type="text/javascript">
	FreshWidget.init("", {"queryString": "&widgetType=popup&formTitle=Feedback+%26+Support&attachFile=no&searchArea=no", "widgetType": "popup", "buttonType": "text", "buttonText": "TELL US WHAT YOU THINK.", "buttonColor": "white", "buttonBg": "#7e5a78", "alignment": "4", "offset": "400px", "formHeight": "500px", "url": "http://nethermead.freshdesk.com"} );
</script>
<% end %>

</body>
</html>

app/views/layouts/search.html.erb
<% content_for :content do %>
    <%= yield %>

    <script type="text/template" id="state-template">
    <div class="state-name">{{= state_full_name }}</div>
    <a href="#">
        <span class="stateface stateface-{{= state_abbreviation }}"></span>
        <span class="glyphicon glyphicon-ok-sign"></span>
    </a>
    </script>

    <script type="text/template" id="states-template">
    <div class="container-fluid container-padded">
    <div class="row">
      <div class="col-md-12">
        <h4><span class="glyphicon glyphicon-map-marker purple"></span> Pick a state</h4>
      </div>
    </div>
    <div class="row sly">
      <div class="col-md-12">
        <div class="controls">
          <span class="glyphicon glyphicon-chevron-left sly-control hidden left"></span>
        </div>
        <div class="frame-container">
          <div class="frame">
            <ul class="slidee list-unstyled list-inline collection-container states clearfix"></ul>
          </div>
          <div class="scrollbar hidden">
              <div class="handle"></div>
          </div>
        </div>
        <div class="controls">
          <span class="glyphicon glyphicon-chevron-right sly-control hidden right"></span>
        </div>
      </div>
    </div>

    </div>
    </script>


    <script type="text/template" id="product-class-template">
    <a href="#"><div class="circle"><div class="product-class-abbr">{{= abbr }}</div></div></a>
    <div class="product-class-name">{{= name }}<br /><span class="glyphicon glyphicon-ok-sign"></span></div>
    </script>

    <script type="text/template" id="product-classes-template">
    <div class="container-fluid background-light-grey container-padded">
    <div class="row">
      <div class="col-md-12">
        <h4><span class="glyphicon glyphicon-list purple"></span> Pick a product class</h4>
      </div>
    </div>
    <div class="row collection-container product-classes-container">
    </div>
    </div>
    </script>

    <script type="text/template" id="company-search-template">
    <div class="container-fluid background-light-grey container-padded">
      <div class="row">
        <div class="col-md-12">
          <h4><span class="glyphicon glyphicon-search purple"></span> Enter Company Name</h4>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <input class="form-control company-name-search" placeholder="ex. Aetna, Blue Cross, Oxford, etc.">
        </div>
      </div>
    </div>

    <div class="market-chooser-container"></div>

    <div class="container-fluid container-padded">
      <div class="row">
        <div class="col-md-12">
            <a href="#" class="btn btn-success btn-lg search-result-button">View results</a>
        </div>
      </div>
    </div>
    </script>


<% end %>
<%= render template: "layouts/application" %>